const assert = require('node:assert/strict')
const fs = require('node:fs')
const http = require('node:http')
const path = require('node:path')
const { chromium } = require('playwright')
const root = path.resolve(__dirname, '../dist')
const chrome = [process.env.CHROME_PATH, chromium.executablePath(), path.join(process.env.PROGRAMFILES || '', 'Google/Chrome/Application/chrome.exe')].find(p => p && fs.existsSync(p))

async function main() {
  const server = http.createServer((req, res) => {
    const file = path.resolve(root, '.' + (new URL(req.url, 'http://localhost').pathname === '/' ? '/index.html' : new URL(req.url, 'http://localhost').pathname))
    if (!file.startsWith(root + path.sep) || !fs.existsSync(file)) { res.writeHead(404); return res.end() }
    res.setHeader('content-type', file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html')
    res.end(fs.readFileSync(file))
  })
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const url = `http://127.0.0.1:${server.address().port}/`
  const browser = await chromium.launch({ executablePath: chrome, headless: true, args: ['--enable-webgl', '--use-angle=swiftshader'] })
  const errors = []
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, locale: 'zh-CN', colorScheme: 'dark' })
  page.on('pageerror', e => errors.push(e.message))
  const scene = page.locator('[data-scene-root]')
  const attr = name => scene.getAttribute('data-scene-' + name)
  const waitAttr = (name, value) => page.waitForFunction(({ name, value }) => document.querySelector('[data-scene-root]')?.getAttribute('data-scene-' + name) === value, { name, value })
  try {
    await page.goto(url)
    await page.getByRole('button', { name: '探索太阳系', exact: true }).waitFor({ timeout: 2500 })
    await waitAttr('ready', 'true')
    assert.equal(await attr('bodies'), '9')
    assert.equal(await attr('planets'), '8')
    assert.equal(await attr('moon'), 'true')
    assert.equal(await attr('saturn-rings'), 'true')
    assert.equal(await page.locator('canvas').count(), 1)
    assert.equal(await page.locator('body').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(5, 5, 7)', 'dark theme is predominantly black')
    if (process.env.SCREENSHOT_DIR) {
      fs.mkdirSync(process.env.SCREENSHOT_DIR, { recursive: true })
      await page.screenshot({ path: path.join(process.env.SCREENSHOT_DIR, 'solar-home-dark.png') })
    }
    await page.evaluate(() => window.scrollTo({ top: 120, behavior: 'instant' }))
    const readingPosition = await page.evaluate(() => scrollY)
    await page.getByRole('button', { name: '探索太阳系', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '探索太阳系' })
    await dialog.waitFor()
    await waitAttr('mode', 'explore')
    assert.equal(await page.locator('.site-shell').evaluate(el => el.inert), true)
    assert.equal(await dialog.getByRole('button', { name: /选择/ }).count(), 9)
    await dialog.getByRole('button', { name: '选择土星', exact: true }).click()
    await waitAttr('selected', 'saturn')
    await page.waitForTimeout(500)
    assert.match(await dialog.locator('.body-detail').innerText(), /土星.*环/s)
    await dialog.getByRole('button', { name: '暂停', exact: true }).click()
    await waitAttr('paused', 'true')
    const time = await attr('time')
    await page.waitForTimeout(180)
    assert.equal(await attr('time'), time, 'paused simulation is stable')
    const before = await attr('camera')
    const distanceBeforeZoom = Number(await attr('camera-distance'))
    await dialog.getByRole('button', { name: '放大', exact: true }).click()
    await page.waitForTimeout(150)
    assert.notEqual(await attr('camera'), before, 'zoom changes the actual camera')
    assert.ok(Number(await attr('camera-distance')) < distanceBeforeZoom, 'zoom in moves closer to the selected body')
    await dialog.getByRole('button', { name: '重置视角', exact: true }).click()
    await waitAttr('selected', 'none')
    assert.equal(await attr('paused'), 'true', 'reset preserves pause state')
    const surface = dialog.locator('.explorer-surface')
    const rect = await surface.boundingBox()
    const cameraBeforeDrag = await attr('camera')
    await page.mouse.move(rect.x + rect.width * .5, rect.y + rect.height * .45)
    await page.mouse.down()
    await page.mouse.move(rect.x + rect.width * .6, rect.y + rect.height * .5, { steps: 8 })
    await page.mouse.up()
    await page.waitForTimeout(250)
    assert.notEqual(await attr('camera'), cameraBeforeDrag, 'drag rotates the camera')
    assert.equal(await attr('selected'), 'none', 'drag does not select a planet')
    await dialog.getByRole('button', { name: '重置视角', exact: true }).click()
    await page.waitForTimeout(180)
    await page.mouse.click(720, 450)
    await waitAttr('selected', 'sun')
    await page.keyboard.press('Escape')
    await dialog.waitFor({ state: 'hidden' })
    await waitAttr('mode', 'browse')
    assert.equal(await attr('paused'), 'false', 'leaving exploration resumes the ambient scene')
    assert.equal(await page.locator('.site-shell').evaluate(el => el.inert), false)
    assert.equal(await page.evaluate(() => scrollY), readingPosition, 'exit restores the reading position')
    assert.equal(await page.locator('body').evaluate(el => el.style.overflow), '')
    assert.equal(await page.getByRole('button', { name: '探索太阳系', exact: true }).evaluate(el => el === document.activeElement), true)
    for (let i = 0; i < 3; i++) {
      await page.getByRole('button', { name: '探索太阳系', exact: true }).click()
      await waitAttr('mode', 'explore')
      assert.equal(await page.locator('canvas').count(), 1)
      assert.equal(await attr('selected'), 'none')
      await page.keyboard.press('Escape')
    }
    for (const [id, phase] of [['home','hero'],['work','projects'],['focus','focus'],['about','about'],['links','links']]) {
      await page.locator('#' + id).evaluate(el => el.scrollIntoView({ block: 'center', behavior: 'instant' }))
      await waitAttr('phase', phase)
    }
    await page.locator('#home').evaluate(el => el.scrollIntoView({ behavior: 'instant' }))
    await page.getByRole('button', { name: '探索太阳系', exact: true }).click()
    await dialog.getByRole('button', { name: '选择地球', exact: true }).click()
    await waitAttr('selected', 'earth')
    if (process.env.SCREENSHOT_DIR) {
      fs.mkdirSync(process.env.SCREENSHOT_DIR, { recursive: true })
      await page.screenshot({ path: path.join(process.env.SCREENSHOT_DIR, 'solar-explorer-desktop.png') })
    }
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Switch to English' }).click()
    await page.getByRole('button', { name: 'Explore the solar system', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Select Neptune', exact: true }).click()
    assert.match(await page.locator('.body-detail').innerText(), /Neptune/)
    await page.keyboard.press('Escape')
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, locale: 'zh-CN' })
    await mobile.goto(url)
    await mobile.waitForFunction(() => document.querySelector('[data-scene-root]')?.getAttribute('data-scene-ready') === 'true')
    await mobile.getByRole('button', { name: '探索太阳系', exact: true }).tap()
    await mobile.getByRole('button', { name: '选择海王星', exact: true }).tap()
    assert.equal(await mobile.locator('[data-scene-root]').getAttribute('data-scene-selected'), 'neptune')
    await mobile.getByRole('button', { name: '暂停', exact: true }).tap()
    const mobileScene = mobile.locator('[data-scene-root]')
    const touch = await mobile.context().newCDPSession(mobile)
    const mobileCamera = await mobileScene.getAttribute('data-scene-camera')
    await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 170, y: 420 }] })
    await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 230, y: 440 }] })
    await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await mobile.waitForTimeout(180)
    assert.notEqual(await mobileScene.getAttribute('data-scene-camera'), mobileCamera, 'one-finger drag rotates the camera')
    const mobileDistance = Number(await mobileScene.getAttribute('data-scene-camera-distance'))
    await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 150, y: 420 }, { x: 240, y: 420 }] })
    await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 100, y: 420 }, { x: 290, y: 420 }] })
    await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await mobile.waitForTimeout(180)
    assert.ok(Number(await mobileScene.getAttribute('data-scene-camera-distance')) < mobileDistance, 'pinch-out zooms closer')
    assert.equal(await mobileScene.getAttribute('data-scene-selected'), 'neptune', 'multi-touch does not accidentally select another planet')
    await touch.detach()
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
    if (process.env.SCREENSHOT_DIR) await mobile.screenshot({ path: path.join(process.env.SCREENSHOT_DIR, 'solar-explorer-mobile.png') })
    await mobile.getByRole('button', { name: '退出探索', exact: true }).tap()
    await mobile.close()

    const reduced = await browser.newPage({ reducedMotion: 'reduce', locale: 'zh-CN' })
    reduced.on('pageerror', e => errors.push(e.message))
    await reduced.goto(url)
    await reduced.waitForFunction(() => document.querySelector('[data-scene-root]')?.getAttribute('data-scene-ready') === 'true')
    await reduced.getByRole('button', { name: '探索太阳系', exact: true }).click()
    await reduced.getByRole('button', { name: '选择木星', exact: true }).click()
    await reduced.waitForFunction(() => document.querySelector('[data-scene-root]')?.getAttribute('data-scene-selected') === 'jupiter')
    await reduced.getByRole('button', { name: '放大', exact: true }).click()
    await reduced.getByRole('region', { name: '太阳系交互视图' }).focus()
    const keyboardCamera = await reduced.locator('[data-scene-root]').getAttribute('data-scene-camera')
    await reduced.keyboard.press('ArrowLeft')
    await reduced.waitForTimeout(100)
    assert.notEqual(await reduced.locator('[data-scene-root]').getAttribute('data-scene-camera'), keyboardCamera, 'keyboard can rotate the scene')
    await reduced.waitForTimeout(150)
    const reducedFrames = await reduced.locator('[data-scene-root]').getAttribute('data-scene-render-count')
    await reduced.waitForTimeout(150)
    assert.equal(await reduced.locator('[data-scene-root]').getAttribute('data-scene-render-count'), reducedFrames, 'reduced-motion exploration renders only on demand')
    for (let i = 0; i < 16; i++) { await reduced.keyboard.press('Tab'); assert.equal(await reduced.getByRole('dialog').evaluate(el => el.contains(document.activeElement)), true) }
    await reduced.keyboard.press('Escape')
    await reduced.close()

    const delayed = await browser.newPage({ locale: 'zh-CN' })
    delayed.on('pageerror', e => errors.push(e.message))
    let release
    const released = new Promise(resolve => { release = resolve })
    await delayed.route(/\/assets\/three\.module-[^/]+\.js$/, async route => { await released; await route.continue() })
    try {
      await delayed.goto(url, { waitUntil: 'domcontentloaded' })
      await delayed.getByRole('button', { name: '探索太阳系', exact: true }).click()
      await delayed.getByRole('button', { name: '选择火星', exact: true }).click()
      await delayed.getByRole('button', { name: '暂停', exact: true }).click()
      release()
      await delayed.waitForFunction(() => { const el = document.querySelector('[data-scene-root]'); return el?.getAttribute('data-scene-mode') === 'explore' && el?.getAttribute('data-scene-selected') === 'mars' && el?.getAttribute('data-scene-paused') === 'true' })
      await delayed.keyboard.press('Escape')
    } finally { release(); await delayed.close() }

    const unsupported = await browser.newPage({ locale: 'zh-CN' })
    await unsupported.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(kind, ...args) { return String(kind).includes('webgl') ? null : original.call(this, kind, ...args) } })
    await unsupported.goto(url)
    await unsupported.waitForFunction(() => document.querySelector('[data-scene-root]')?.getAttribute('data-scene-fallback') === 'active')
    assert.equal(await unsupported.getByRole('button', { name: '探索太阳系', exact: true }).isDisabled(), true)
    assert.equal(await unsupported.locator('.fallback-solar i').count(), 8)
    await unsupported.close()
    await page.evaluate(() => document.querySelector('canvas').dispatchEvent(new Event('webglcontextlost', { cancelable: true })))
    await waitAttr('fallback', 'active')
    assert.equal(await page.getByRole('button', { name: 'Explore the solar system', exact: true }).isDisabled(), true)
    assert.deepEqual(errors, [])
    console.log('solar system exploration passed')
  } finally {
    await browser.close()
    await new Promise(resolve => server.close(resolve))
  }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
