const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const http = require('node:http')
const { chromium } = require('playwright')

async function main() {
  const root = path.resolve(__dirname, '../dist')
  const server = http.createServer((req, res) => {
    const pathname = new URL(req.url, 'http://localhost').pathname
    const file = path.resolve(root, '.' + (pathname === '/' ? '/index.html' : pathname))
    if (!file.startsWith(root + path.sep) || !fs.existsSync(file)) { res.writeHead(404); return res.end() }
    res.setHeader('content-type', file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : file.endsWith('.webp') ? 'image/webp' : 'text/html')
    res.end(fs.readFileSync(file))
  })
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const url = `http://127.0.0.1:${server.address().port}/`
  const executablePath = [process.env.CHROME_PATH, chromium.executablePath(), path.join(process.env.PROGRAMFILES || '', 'Google/Chrome/Application/chrome.exe')].find(p => p && fs.existsSync(p))
  const browser = await chromium.launch({ executablePath, args: ['--enable-webgl', '--use-angle=swiftshader'] })
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, locale: 'zh-CN', colorScheme: 'dark' })
  const errors = [], loaded = new Set()
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error' && /THREE|shader|WebGL/.test(message.text())) errors.push(message.text()) })
  page.on('response', response => { if (/\/assets\/solar\/.*\.webp$/.test(response.url()) && response.ok()) loaded.add(response.url()) })
  const scene = page.locator('[data-scene-root]')
  try {
    await page.goto(url)
    await page.waitForFunction(() => document.querySelector('[data-scene-root]')?.dataset.sceneReady === 'true')
    assert.equal(await scene.getAttribute('data-scene-textures'), '14', 'all planet, cloud, night, ring and sky maps decoded')
    assert.equal(loaded.size, 14, 'textures are self-hosted and loaded after the scene chunk')
    await page.getByRole('button', { name: '探索太阳系', exact: true }).click()
    assert.equal(await page.locator('.celestial-label').count(), 9)
    await page.getByRole('button', { name: '选择地球', exact: true }).click()
    await page.waitForFunction(() => { const value = Number(document.querySelector('[data-scene-root]')?.dataset.sceneFlightProgress); return value > .15 && value < .75 })
    const intermediate = Number(await scene.getAttribute('data-scene-camera-distance'))
    await page.waitForFunction(() => document.querySelector('[data-scene-root]')?.dataset.sceneFlightProgress === '1.000')
    const settled = Number(await scene.getAttribute('data-scene-camera-distance'))
    assert.ok(intermediate > settled * 2, 'selection flies toward the planet instead of teleporting')
    assert.match(await page.locator('.body-detail').innerText(), /12,756/)
    await page.getByRole('button', { name: '重置视角', exact: true }).click()
    await page.waitForFunction(() => document.querySelector('[data-scene-root]')?.dataset.sceneSelected === 'none')
    const landscapeDistance = Number(await scene.getAttribute('data-scene-camera-distance'))
    await page.setViewportSize({ width: 390, height: 844 })
    await page.waitForFunction(distance => Number(document.querySelector('[data-scene-root]')?.dataset.sceneCameraDistance) > distance * 1.5, landscapeDistance)
    const portraitDistance = Number(await scene.getAttribute('data-scene-camera-distance'))
    await page.getByRole('button', { name: '重置视角', exact: true }).click()
    await page.waitForTimeout(100)
    assert.ok(Math.abs(Number(await scene.getAttribute('data-scene-camera-distance')) - portraitDistance) < .1, 'resize already fits the whole system without requiring reset')
    await page.keyboard.press('Escape')
    await page.close()

    // Actions issued while images are delayed must reach the eventual controller.
    const delayed = await browser.newPage({ locale: 'zh-CN' })
    let release
    const gate = new Promise(resolve => { release = resolve })
    await delayed.route('**/assets/solar/*.webp', async route => { await gate; await route.continue() })
    try {
      await delayed.goto(url, { waitUntil: 'domcontentloaded' })
      await delayed.getByRole('button', { name: '探索太阳系', exact: true }).click()
      await delayed.getByRole('button', { name: '选择土星', exact: true }).click()
      await delayed.getByRole('button', { name: '暂停', exact: true }).click()
      release()
      await delayed.waitForFunction(() => { const s = document.querySelector('[data-scene-root]')?.dataset; return s?.sceneReady === 'true' && s.sceneSelected === 'saturn' && s.scenePaused === 'true' })
      await delayed.keyboard.press('Escape')
    } finally { release(); await delayed.close() }

    const missing = await browser.newPage({ locale: 'zh-CN' })
    await missing.route('**/assets/solar/earth_daymap.webp', route => route.fulfill({ status: 404, body: '' }))
    await missing.goto(url)
    await missing.waitForFunction(() => document.querySelector('[data-scene-root]')?.dataset.sceneFallback === 'active')
    assert.equal(await missing.getByRole('button', { name: '探索太阳系', exact: true }).isDisabled(), true)
    await missing.close()

    const short = await browser.newPage({ viewport: { width: 320, height: 568 }, locale: 'en-US', isMobile: true, hasTouch: true })
    await short.goto(url)
    await short.getByRole('button', { name: 'Explore the solar system', exact: true }).click()
    await short.getByRole('button', { name: 'Select Earth', exact: true }).click()
    const detail = short.locator('.body-detail')
    await short.waitForFunction(() => document.querySelector('[data-scene-root]')?.dataset.sceneSelected === 'earth')
    assert.ok((await detail.boundingBox()).height < 110, 'short screens reserve space for the planet')
    assert.equal(await short.locator('.body-facts').isVisible(), false)
    await short.getByRole('button', { name: 'Body details', exact: true }).tap()
    assert.equal(await short.locator('.body-facts').isVisible(), true, 'facts remain available on small screens')
    await short.getByRole('button', { name: 'Body details', exact: true }).tap()
    const touchTarget = await short.getByRole('button', { name: 'Select Earth', exact: true }).boundingBox()
    assert.ok(touchTarget.width >= 44 && touchTarget.height >= 44)
    await short.setViewportSize({ width: 844, height: 390 })
    await short.waitForTimeout(200)
    const infoBox = await detail.boundingBox(), picker = await short.locator('.planet-picker').boundingBox()
    assert.ok(infoBox.y + infoBox.height < picker.y, 'landscape controls and information do not overlap')
    await short.close()
    for (const [width, height] of [[800, 900], [820, 1180]]) {
      const tablet = await browser.newPage({ viewport: { width, height }, locale: 'en-US', reducedMotion: 'reduce' })
      await tablet.goto(url)
      await tablet.waitForFunction(() => document.querySelector('[data-scene-root]')?.dataset.sceneReady === 'true')
      assert.equal(await tablet.locator('[data-scene-root]').getAttribute('data-scene-outside-bodies'), 'none', `all eight planets fit the ${width}x${height} hero`)
      await tablet.close()
    }
    for (const [width, height] of [[1024, 400], [1440, 450], [1366, 768]]) {
      const shallow = await browser.newPage({ viewport: { width, height }, locale: 'en-US', reducedMotion: 'reduce' })
      await shallow.goto(url)
      await shallow.getByRole('button', { name: 'Explore the solar system', exact: true }).click()
      await shallow.getByRole('button', { name: 'Select Earth', exact: true }).click()
      await shallow.waitForFunction(() => document.querySelector('[data-scene-root]')?.dataset.sceneSelected === 'earth')
      const panel = await shallow.locator('.body-detail').boundingBox(), toolbar = await shallow.locator('.planet-picker').boundingBox()
      assert.ok(panel.y + panel.height < toolbar.y, `information clears the toolbar at ${width}x${height}`)
      assert.equal(await shallow.getByRole('button', { name: 'Body details', exact: true }).isVisible(), true)
      await shallow.close()
    }
    assert.deepEqual(errors, [], 'shader compilation must succeed')
    console.log('solar visual quality, camera flight and texture lifecycle passed')
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)) }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
