import { motion, useReducedMotion, useScroll, useTransform } from 'motion/react'
import { useRef } from 'react'

const links = { code: '/Code/', math: 'https://github.com/tangyixiao/HighSchoolMathematics', agents: 'https://github.com/tangyixiao/Agent-Learning-Hub', github: 'https://github.com/tangyixiao', luogu: 'https://www.luogu.com.cn/blog/TangyixiaoQAQ/', cnblogs: 'https://home.cnblogs.com/u/TangyixiaoQAQ', csdn: 'https://blog.csdn.net/DCMyyds', bilibili: 'https://space.bilibili.com/512272131' }
const focus = [{ n: '01', title: 'Algorithms & Data Structures', zh: '算法与数据结构', text: '把抽象问题写成经得起边界检验的程序。', href: links.code }, { n: '02', title: 'Mathematics', zh: '数学', text: '用证明、结构和直觉理解复杂系统。', href: links.math }, { n: '03', title: 'Intelligent Systems', zh: '智能系统', text: '持续记录模型、工具与学习方法。', href: links.agents }]
const projects = [{ id: 'code', kind: 'COMPETITIVE ARCHIVE', title: 'CodeHub', href: links.code, text: '2,700+ 份竞赛代码与题解，支持检索、配对阅读与 LaTeX。' }, { id: 'math', kind: 'STUDY SYSTEM', title: 'HighSchool Mathematics', href: links.math, text: '面向长期学习的数学资料、讲义与思考。' }, { id: 'agents', kind: 'RESEARCH NOTES', title: 'Agent Learning Hub', href: links.agents, text: '关于智能体、工具调用与评估的学习记录。' }]
function Fade({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) { const reduce = useReducedMotion(); return <motion.div initial={reduce ? false : { opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ delay, duration: .6 }}>{children}</motion.div> }
function App() { return <main><header className="hero" id="home"><nav><a className="brand" href="#home">TYX<span>.</span></a><div><a href="#about">About</a><a href="#work">Work</a><a href="#links">Links</a></div></nav><div className="hero-grid" aria-hidden="true"><i /><i /><i /><i /><i /></div><div className="hero-copy"><Fade><p className="code-label">// PERSONAL SYSTEM / 2026</p><h1>TANG<br /><em>YI XIAO</em></h1><p className="lede">探索算法、数学与智能。<br />Build systems. Learn in public.</p><a className="blue-button" href="#work">查看项目 <span>↓</span></a></Fade></div><div className="hero-foot"><span>COMPETITIVE PROGRAMMING · MATHEMATICS · INTELLIGENT SYSTEMS</span><span>SCROLL TO EXPLORE ↓</span></div></header><section className="ticker" aria-label="关注主题"><div>{Array(3).fill('ALGORITHMS · MATHEMATICS · OPEN LEARNING · CODE AS THINKING · ').join('')}</div></section><section className="about section" id="about"><Fade><p className="code-label">01 / ABOUT</p><h2>不追逐噪音，<br /><em>构建可复用的理解。</em></h2><p className="about-text">我将竞赛训练、数学推导与智能系统学习视为同一件事：把问题拆解、验证、记录，并在下一次面对它时做得更清晰。这里收集我持续迭代的过程与成果。</p><a className="text-link" href={links.github} target="_blank" rel="noreferrer">GitHub profile ↗</a></Fade></section><section className="focus" id="focus"><div className="section-head"><p className="code-label">02 / FOCUS AREAS</p><h2>Work modes</h2></div>{focus.map((item, i) => <Fade key={item.n} delay={i * .08}><a className="focus-row" href={item.href} target={item.href.startsWith('http') ? '_blank' : undefined} rel="noreferrer"><span>{item.n}</span><div><strong>{item.title}</strong><b>{item.zh}</b></div><p>{item.text}</p><i>↗</i></a></Fade>)}</section><section className="work section" id="work"><div className="section-head"><p className="code-label">03 / SELECTED WORK</p><h2>Projects with <em>memory.</em></h2></div><div className="project-stack">{projects.map((project, index) => <ProjectCard key={project.id} project={project} index={index} />)}</div></section><footer id="links"><div><p className="code-label">04 / CONTINUE</p><h2>Keep the thread<br /><em>open.</em></h2></div><div className="link-grid"><a href={links.code}>CodeHub <span>↗</span></a><a href={links.github} target="_blank" rel="noreferrer">GitHub <span>↗</span></a><a href={links.luogu} target="_blank" rel="noreferrer">Luogu <span>↗</span></a><a href={links.cnblogs} target="_blank" rel="noreferrer">Cnblogs <span>↗</span></a><a href={links.csdn} target="_blank" rel="noreferrer">CSDN <span>↗</span></a><a href={links.bilibili} target="_blank" rel="noreferrer">Bilibili <span>↗</span></a></div><p className="copyright">© 2026 TANG YIXIAO · BUILT FOR CONTINUOUS LEARNING</p></footer></main> }
function ProjectCard({ project, index }: { project: typeof projects[number]; index: number }) { const ref = useRef<HTMLElement>(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start end', 'start start'] }); const reduce = useReducedMotion(); const scale = useTransform(scrollYProgress, [0, 1], [1, reduce ? 1 : .94 + index * .025]); return <article ref={ref} className="project-wrap"><motion.a style={{ scale }} href={project.href} className="project-card" target={project.href.startsWith('http') ? '_blank' : undefined} rel="noreferrer"><div className="project-no">0{index + 1}</div><div className="project-body"><p>{project.kind}</p><h3>{project.title}</h3><span>{project.text}</span></div><div className="project-art"><i /><i /><i /><b>OPEN<br />PROJECT ↗</b></div></motion.a></article> }
export default App
